project_id = "suueubckrgtiniymoxio"

[auth]
site_url = "https://suueubckrgtiniymoxio.supabase.co"

[functions.generate-event-description]
verify_jwt = true

[functions.notify-admin-new-event]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-event-approval-notification]
verify_jwt = false

[functions.handle-event-approval]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true

[functions.contact-organizer]
verify_jwt = false

[functions.notify-subscribers]
verify_jwt = false


[functions.verify-captcha]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false
